Hanimation.Text.prototype.adjustBound=function(){var d=this.getParam(),b=document.getElementById("canvasPanel"),c=document.getElementById("canvasBuffer");c.width=Math.max(d.width,b.width);c.height=Math.max(d.height,b.height);var a=c.getContext("2d");a.clearRect(0,0,c.width,c.height);var b=(c.width-d.width)/2,e=(c.height-d.height)/2;this.isConverting=true;a.save();a.translate(b,e);this.draw(a,0);a.restore();this.isConverting=false;for(var f=a.getImageData(0,0,c.width,c.height),a=f.data,f=d=f.width,
h,j=0,k=0,i=0,g=c.width*4,i=(e-1)*g;i>=0;){h=scanLine(a,i,c.width);if(h.left==c.width)break;else{if(h.left<d)d=h.left;if(h.right<f)f=h.right;j++}i-=g}for(var i=e*g,l=c.height-e,e=0;e<l;){h=scanLine(a,i,c.width);if(h.left==c.width){if(j==0&&k++,e>0)break}else{e++;if(h.left<d)d=h.left;if(h.right<f)f=h.right}i+=g;if(i<0)break}a={};a.deltaX=d-b;a.deltaY=j>0?-j:k;a.width=c.width-f-d;a.height=j+e;return a};
Hanimation.Text.prototype.convertToImage=function(){var d=this.adjustBound(),b=this.getParam();b.left+=d.deltaX;b.top+=d.deltaY;b.width=d.width;b.height=d.height;b.right=b.left+b.width;b.bottom=b.top+b.height;b.startX=b.left;b.startY=b.top;var c=document.getElementById("canvasBuffer");c.width=d.width;c.height=d.height;var a=c.getContext("2d");a.clearRect(0,0,c.width,c.height);this.isConverting=true;a.save();a.translate(-d.deltaX,-d.deltaY);this.draw(a,0);a.restore();this.isConverting=false;a=c.toDataURL("image/png");
this.dataRef.param.imageSrc=c.toDataURL("image/png");return{left:b.left,top:b.top,width:d.width,height:d.height,data:a}};Hanimation.Text.prototype.isValid=function(){return true};Hanimation.Text.prototype.setEndPoint=function(d,b,c){d=this.adjustPosition(d,b,c,0);this.editStartX=d.x;this.editStartY=d.y;this.editEndX=d.x+this.textWidth;this.editEndY=d.y+this.textHeight};
Hanimation.Text.prototype.setEditStartPoint=function(d,b,c,a){Hanimation.AniObject.prototype.setEditStartPoint.call(this,d,b,c,a);this.prevFontSize=this.dataRef.param.fontSize};Hanimation.Text.prototype.setEditEndPoint=function(d,b,c,a){d=Hanimation.AniObject.prototype.setEditEndPoint.call(this,d,b,c,a);d=Math.max(d.scaleX,d.scaleY);this.dataRef.param.fontSize=Math.floor(this.prevFontSize*d)};Hanimation.Group.prototype.supportPivot=function(){return true};
Hanimation.Group.prototype.cleanObjects=function(){for(var d=[],b=[],c=this.dataRef.items.length,a,e=0,f=0;f<c;f++)a=this.dataRef.items[f],b[a.guid]||(d[e]=a,e++,b[a.guid]=1);c=d.length;this.dataRef.items=[];for(f=0;f<c;f++)this.dataRef.items[f]=d[f]};
Hanimation.Group.prototype.restoreObjects=function(d){for(var b=this.dataRef.items.length,c=this.getParam(),a=this.getLiveParam(),e=[],f=a.endX-a.startX,a=a.endY-a.startY,f=d?1:f/c.rawWidth,a=d?1:a/c.rawHeight,h=c.left+c.rotateCenterX,j=c.top+c.rotateCenterY,d=d?0:c.rotate,k,i=0;i<b;i++){k=getAniObject(this.dataRef.items[i]);k.setScale(f,a,true);k.updateBoundRect();k.setAlpha(1,true);var g=k.getParam(),l=g.startX>g.endX,t=g.startY>g.endY,r=0,s=0;if(g.startX>g.endX)r=g.width;if(g.startY>g.endY)s=g.height;
if(!k.needRotateUpdate()&&Math.abs(d)>0.0010){var m=c.startX+(g.left+g.rotateCenterX)-h,u=c.startY+(g.top+g.rotateCenterY)-j,n=g.rotateCenterX,o=g.rotateCenterY,q=h+m*Math.cos(d)-u*Math.sin(d),m=j+m*Math.sin(d)+u*Math.cos(d),n=q-n,o=m-o,q=n+g.width,m=o+g.height;g.startX=l?q:n;g.startY=t?m:o;g.endX=!l?q:n;g.endY=!t?m:o;g.rotate+=d}else g.startX+=c.startX,g.startY+=c.startY,g.endX+=c.startX,g.endY+=c.startY;g.left=Math.min(g.startX,g.endX);g.top=Math.min(g.startY,g.endY);g.right=Math.max(g.startX,g.endX);
g.bottom=Math.max(g.startY,g.endY);(r!=0||s!=0)&&k.offset(r,s)}for(i=0;i<b;i++)k=getAniObject(this.dataRef.items[i]),k.setRotate(h,j,d),e[i]=k;return e};Hanimation.Group.prototype.regroupObjects=function(){var d=this.restoreObjects();this.clearObjects();for(var b=d.length,c=0;c<b;c++){var a=d[c];if(a){var e=a.dataRef;e.items&&e.items.length&&a.regroupObjects();this.addObject(d[c])}}this.getRawBound();this.getParam().rotate=0};Hanimation.Group.prototype.clearObjects=function(){this.dataRef.items=[]};
Hanimation.Group.prototype.addObjects=function(d){for(var b=d.length,c=null,c=null,a=0;a<b;a++)c=d[a],c=getAniObject(c),this.addObject(c)};
Hanimation.Group.prototype.getRawBound=function(){var d=this.dataRef.items.length,b=this.getParam();b.left=Hanimation.MAX_VALUE;b.top=Hanimation.MAX_VALUE;b.right=Hanimation.MIN_VALUE;b.bottom=Hanimation.MIN_VALUE;for(var c,a,e=0;e<d;e++)a=getAniObject(this.dataRef.items[e]),c=a.getBoundRect(),this.updateBound(c.left,c.top),this.updateBound(c.right,c.bottom);b.startX=b.left;b.startY=b.top;b.endX=b.right;b.endY=b.bottom;b.width=Math.max(1,b.right-b.left);b.height=Math.max(1,b.bottom-b.top);b.rawWidth=
b.width;b.rawHeight=b.height;for(e=0;e<d;e++){a=getAniObject(this.dataRef.items[e]);c=a.getBoundRect(true);a=a.getParam();var f=a.startX>a.endX,h=a.startY>a.endY,j=c.left-b.startX,k=c.top-b.startY,i=c.right-b.startX;c=c.bottom-b.startY;a.startX=f?i:j;a.startY=h?c:k;a.endX=f?j:i;a.endY=h?k:c;a.left=Math.min(a.startX,a.endX);a.right=Math.max(a.startX,a.endX);a.top=Math.min(a.startY,a.endY);a.bottom=Math.max(a.startY,a.endY);a.width=a.right-a.left;a.height=a.bottom-a.top}(typeof b.rotateCenterX=="undefined"||
b.rotateCenterY=="undefined")&&this.setRotateBase((b.left+b.right)/2,(b.top+b.bottom)/2)};function getRenderBuffer(d,b,c,a){var e=document.getElementById("canvasBuffer");e.width=par.width;e.height=par.height;var f=e.getContext("2d");f.clearRect(0,0,e.width,e.height);d.draw(f,b);return f.getImageData(0,0,c,a)}Hanimation.Scene=function(d){this.aryCurrentUnit=[];this.layers=d||[];this.currentFrame=0;this.resetScene()};inherit(Hanimation.Scene,Hanimation.AniObject);
Hanimation.Scene.prototype.resetScene=function(){for(var d=this.layers.length,b=0;b<d;b++)this.aryCurrentUnit[b]=0;this.setActiveFrame(0)};Hanimation.Scene.prototype.nextFrame=function(){this.setActiveFrame(this.currentFrame+1)};Hanimation.Scene.prototype.prevFrame=function(){this.setActiveFrame(this.currentFrame-1)};
Hanimation.Scene.prototype.setActiveFrame=function(d){for(var d=Math.max(0,d),b=this.layers.length,c=0;c<b;c++){var a=this.layers[c],e=this.aryCurrentUnit[c];e||(e=0);for(var e=Math.max(0,Math.min(a.units.length-1,e)),f=a.units[e];f;)if(d>=f.frameStart&&d<f.frameStart+f.frameCount)break;else d<f.frameStart?e--:e++,f=a.units[e];this.aryCurrentUnit[c]=e}};
Hanimation.Scene.prototype.draw=function(d){p||(p={});if(!p.layers)p.layers=this.aniLayers;if(!p.canvas)p.canvas=this.objCanvas;if(p.repair)p.layers=buildLayers(p.layers);var b=p.canvas;b.width=b.offsetWidth;b.height=b.offsetHeight;d=b.getContext("2d");d.save();var c=Zoom.getZoomInfo(this.aniData,this.currentFrame);this.prevZoomInfo=JSON.clone(c);d.translate(-c.offsetLeft,-c.offsetTop);if(p.color)d.fillStyle=p.color,d.fillRect(0,0,b.offsetWidth,b.offsetHeight);if(!p.clear){for(var a=0,e=0,f=this.currentFrame,
h,j,k=p.layers,i=k.length-1;i>=0;i--)if(j=k[i],!j.hide)for(var e=j.units.length,g=0;g<e;g++)if(c=j.units[g],a=c.objects.length,c&&a&&f>=c.frameStart&&f<c.frameStart+c.frameCount)for(var l=0;l<a;l++){b=c.objects[l];if(c.animated&&a==1)if(JSON.clone(b.param),h=TimelineUnit.getKeyframe(c,f))Param.exchange(h.param,b.param,true);else if(h=TimelineUnit.getTweenParam(c,f))Param.exchange(h,b.param,true),window.isAniTween=true;b=getAniObject(b);b.draw(d,0)}if(!this.isDrawing)setFocusObjects(d),aniDataIsChange(),
setMenuStatus(),window.isEditSymbol?Symbol.updateImage(window.aniSymbol):window.aniData.layers=aniLayers;d.restore()}};
HaniSVG={exportSVG:function(d){for(var d=JSON.clone(d),b=this.defs="",c=d.layers,a=window.currentFrame||0,e=c.length-1;e>=0;e--){var f=c[e].units;b+='<g layer="'+e+'">';for(var h=0;h<f.length;h++){var j=f[h];if(!(a<j.frameStart||a>j.frameStart+j.frameCount))for(var k=j.objects,i=0;i<k.length;i++){var g=k[i];if(j.animated)g.param=TimelineUnit.getTweenParam(j,a);if(g.items&&g.items.length){var l=getAniObject(g);if(l)l.regroupObjects(),g=l.dataRef}b+=this.createShapes(g)}}b+="</g>"}return b='<svg width="'+
d.width+'" height="'+d.height+'" style="background:'+d.color+';" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs>'+this.defs+"</defs>"+b+"</svg>"},createShapes:function(d){if(d.items&&d.items.length){for(var b=d.param,b='<g transform="translate('+b.left+","+b.top+") rotate("+b.rotate*180/Math.PI+","+b.rotateCenterX+","+b.rotateCenterY+") scale("+(b.width/b.rawWidth||1)+","+(b.height/b.rawHeight||1)+')">',c=0;c<d.items.length;c++){var a=d.items[c];
b+=a.items&&a.items.length?this.createShapes(a):this.createShape(a)}b+="</g>";return b}return this.createShape(d)},createShape:function(d){var b="",c="",a=d.param,e=d.curve.points;if(!a.width&&!a.height)return"";var f=a.fillInfo;if(f)if(c=f.fillColors,f.fillStyle==0)var h=c[0],c="rgba("+[h.r,h.g,h.b,h.a].join(",")+")";else{var j=d.guid,k=f.fillStyle==1,i=k?"linearGradient":"radialGradient",h=f.fillStartPos,f=f.fillEndPos;k?this.defs+="<"+i+' id="'+j+'" x1="'+h.x/a.width+'" y1="'+h.y/a.height+'" x2="'+
f.x/a.width+'" y2="'+f.y/a.height+'" >':(k=a.width/a.height,f=Math.sqrt(Math.pow(h.x-f.x,2)+Math.pow(h.y-f.y,2))/a.width,this.defs+="<"+i+' id="'+j+'" gradientTransform="scale(1,'+k+')" cx="'+h.x/a.width*100+'%" cy="'+h.y/a.height*100+'%" r="'+f+'">');for(f=0;f<c.length;f++)h=c[f],this.defs+='<stop offset="'+h.p*100+'%" style="stop-color:rgb('+h.r+","+h.g+","+h.b+");stop-opacity:"+h.a+'"/>';this.defs+="</"+i+">";c="url(#"+j+")"}f=h=i=j="";switch(d.type){case Hanimation.SHAPE_TEXT:j="text";h+='<tspan x="0" dy="1em">'+
a.textContent+"</tspan>";i+=' style="font-family:'+a.fontFamily+";font-size:"+a.fontSize+";font-weight:"+a.fontWeight+";font-style:"+a.fontStyle+';"';a.rotate&&(f=" rotate("+a.rotate*180/Math.PI+","+a.width/2+","+a.height/2+")");break;case Hanimation.SHAPE_PICTURE:j="image";i+=' xlink:href="'+a.imageSrc+'" height="'+a.height+'" width="'+a.width+'"';break;default:j="path",i+=' d="'+this.convertToSVG(e,d.curve.closed)+'"'}c&&(i+=' fill="'+c+'"');b+="<"+j+' transform="translate('+a.left+","+a.top+")"+
f+'"';a.strokeColor&&(b+=' stroke="'+a.strokeColor+'"');a.lineWidth!=void 0&&(b+=' stroke-width="'+a.lineWidth+'"');a.alpha!=void 0&&(b+=' opacity="'+a.alpha+'"');a.lineCap&&(b+=' stroke-linecap="'+a.lineCap+'"');a.lineJoin&&(b+=' stroke-linejoin="'+a.lineJoin+'"');b+=i+">"+h+"</"+j+">";return b},convertToSVG:function(d,b){for(var c="",a=d.length,e=0;e<a;e++){var f=d[e],h=d[e==d.length-1?0:e+1],j=f.x==void 0;e==0&&(c+=j?"M"+f.nodeX+" "+f.nodeY:"M"+f.x+" "+f.y);if(j){if(!b&&e==a-1)break;c+=" C"+[f.forwardX,
f.forwardY,h.backwardX,h.backwardY,h.nodeX,h.nodeY].join(" ")}else c+=" T"+[f.x,f.y].join(" ")}return c},convertToCurve:function(d){d=d.match(/[A-Za-z]([^A-Za-z]+)/gi);if(!d)return svg;for(var b=[],c=0;c<d.length;c++)d[c]=d[c].replace(/\s*[A-Za-z]\s*/gi,"").split(" ");for(c=0;c<d.length;c++){var a=d[c];if(a.length==2)b.push({x:parseFloat(a[0]),y:parseFloat(a[1])});else{var e=d[c==0?d.length-1:c-1];b.push({forwardX:parseFloat(a[0]),forwardY:parseFloat(a[1]),backwardX:parseFloat(e[2]),backwardY:parseFloat(e[3]),
nodeX:parseFloat(e[4]),nodeY:parseFloat(e[5])})}}return b}};function getBoundary(d,b){var c=d.width,a=d.height,e={};b.width/b.height>c/a?(e.width=c,e.height=b.height*c/b.width,e.left=0,e.top=(a-e.height)/2):(e.height=a,e.width=b.width*a/b.height,e.left=(c-e.width)/2,e.top=0);return e};
